version: "2.3"

services:
    trtis:
        container_name: triton
        build: 'server'
        runtime: nvidia
        hostname: trtis
        restart: always

        oom_kill_disable: true
        privileged: true
        tty: true

        expose:
            - "8000-8002"
                
        networks:
            - back-tier

    controller:
        container_name: controller
        build: 'client/'
        restart: always
        depends_on:
            trtis:
                condition: service_started

        oom_kill_disable: true
        privileged: true
        tty: true
        volumes:
            - ./client:/demo
        working_dir: /demo

        networks:
            - back-tier

networks:
    back-tier:
        driver: bridge



